import ThemeRegistry from './components/themeregistry';

export const metadata = {
  title: 'Neves Arts',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body style={{ overflowX: 'hidden' }}>
        <ThemeRegistry>{children}</ThemeRegistry>
      </body>
    </html>
  );
}
